server:
  port: 8085
spring:
  application:
    name: user-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    url: jdbc:mysql:///shop
    username: root
    password: 123456
  rabbitmq:
   # host: 192.168.1.135
    host: 192.168.236.129
    port: 5672
    username: shop
    password: shop
  redis:
#    jedis:
#      pool:
#        max-active: 100
#        max-wait: 10000
#        max-idle: 10
    host: 192.168.1.135
    #host: 192.168.236.129
    port: 6379
    password: shop
    timeout: 5000
mybatis:
  type-aliases-package: com.shop.user.pojo