server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.1.135
    #host: 192.168.236.129
    port: 5672
    username: shop
    password: shop
  redis:
    #    jedis:
    #      pool:
    #        max-active: 100
    #        max-wait: 10000
    #        max-idle: 10
    host: 192.168.1.135
    #host: 192.168.236.129
    port: 6379
    password: shop
    timeout: 5000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-expiration-duration-in-seconds: 15 #过期时间
    lease-renewal-interval-in-seconds: 5 #心跳时间