server:
  port: 8081
spring:
  application:
    name: item-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    url: jdbc:mysql:///shop
    username: root
    password: 123456
  rabbitmq:
    host: 192.168.1.135
    port: 5672
    username: shop
    password: shop


mybatis:
  type-aliases-package: com.shop.item.pojo