server:
  port: 10010
spring:
  application:
    name: shop-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
zuul:
  routes:
    item-service: /item/**
    upload-service: /upload/**
    search-service: /search/**
    user-service: /user/**
    cart-service: /cart/**
    order-service: /order/**
  prefix: /api
  sensitive-headers:  #允许带头信息
  add-host-header: true #携带域名信息
