server:
  port: 8083
spring:
  application:
    name: search-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  data:
    elasticsearch:
      cluster-nodes: 192.168.236.129:9300
      #cluster-nodes: localhost:9300
      cluster-name: elasticsearch
  rabbitmq:
    host: 192.168.1.135
    port: 5672
    username: shop
    password: shop
